# The following redirect is intended for use with most SPAs that handle
# routing internally.

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  functions = "netlify/functions/"
  publish = "/"

[build.environment]
  TZ = "Asia/Bangkok"